// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    // 1. Jetzt wird die echte index.md ganz oben festgepinnt
    {
      type: 'doc',
      id: 'index', 
      label: '🏠 Startseite',
    },
    // 2. Danach folgen alle Unterordner
    {
      type: 'autogenerated',
      dirName: '.', 
    },
  ],
};

export default sidebars;