// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    // 1. Die echte index.md händisch ganz oben festpinnen
    {
      type: 'doc',
      id: 'index', 
      label: '🏠 Startseite',
    },
    // 2. Den gesamten Ordner scannen, aber die index.md für den Rest des Menüs ignorieren
    {
      type: 'autogenerated',
      dirName: '.',
      // Das sorgt dafür, dass die index-Datei nicht noch mal unten landet:
      customProps: {
        sidebarOptions: {
          exclude: ['index'],
        },
      },
    },
  ],
};

export default sidebars;