// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    // 1. Die echte index.md wird händisch ganz oben als Startseite verankert
    {
      type: 'doc',
      id: 'index', 
      label: '🏠 Startseite',
    },
    // 2. Wir laden die Ordner explizit einzeln über den Autogenerator.
    // Dadurch ignorieren wir lose Dateien im Hauptverzeichnis komplett!
    {type: 'autogenerated', dirName: '1-recht-orga'},
    {type: 'autogenerated', dirName: '2-dsdz'},
    {type: 'autogenerated', dirName: '3-technik-schulhaus'},
    {type: 'autogenerated', dirName: '4-technik-klassenzimmer'},
    {type: 'autogenerated', dirName: '5-bycs'},
    {type: 'autogenerated', dirName: '6-software'},
    {type: 'autogenerated', dirName: '7-vorlagen'},
  ],
};

export default sidebars;